version: "3.8"

services:
  brain-tumor-api:
    build: .
    container_name: brain-tumor-container
    ports:
      - "5000:5000"
    volumes:
      - ./checkpoints:/app/checkpoints
      - ./data:/app/data
      - ./static:/app/static
      - ./templates:/app/templates
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    # Chạy server với các checkpoint rỗng, để app tự động tìm file .pth mới nhất
    command: >
      python app.py
    restart: unless-stopped
