version: "3.8"

services:
  brain-tumor-api:
    build: .
    container_name: brain-tumor-container
    ports:
      - "5000:5000"
    volumes:
      - ./checkpoints:/app/checkpoints
      - ./data:/app/data
      - ./static:/app/static
      - ./templates:/app/templates
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    # Chạy server với các checkpoint mặc định đã huấn luyện
    command: >
      python app.py 
      --resnet checkpoints/resnet50/20260314_130801/resnet50_best.pth 
      --effnet checkpoints/efficientnet/20260314_130441/efficientnet_best.pth
      --convnext checkpoints/convnext_small/20260320_081724/convnext_small_best.pth `
      --effnet_v2 checkpoints/efficientnet_v2_s/20260320_091400/efficientnet_v2_s_best.pth `
      --swin_t checkpoints/swin_t/20260325_092905/swin_t_best.pth
    restart: unless-stopped
